# These are supported funding model platforms

github: goshantmeher # Replace with up to 4 GitHub Sponsors-eligible usernames


# You can uncomment any of the following to add more sponsorship links:
#
# patreon: your_patreon_username
# open_collective: your_open_collective_username
# ko_fi: your_kofi_username
# tidyhq: your_tidyhq_username
# liberapay: your_liberapay_username
# issuehunt: your_issuehunt_username
# otechie: your_otechie_username
# lfx_crowdfunding: your_lfx_crowdfunding_name
# buy_me_a_coffee: your_buy_me_a_coffee_username
# custom: ['https://paypal.me/your_paypal_username', 'https://your_custom_link.com']
